version: "3"

services:
  am-ims:
    image: 218291069433.dkr.ecr.us-east-1.amazonaws.com/amweb:f1a3d38
    container_name: am-ims
    environment:
      - IMS_HOME = <ABSOLUTE_PATH_TO_PROJECT_ROOT>
      - IMS_BACKEND_HOST=http://localhost:8088/api/
      - IMS_API_PORT=8088
      - PGHOST=localhost
      - PGPORT=5432
      - PGDATABASE=ims
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://localhost:5432/ims
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - EXPOSED_DATABASE_PORT=5432
      - EXPOSED_KAFKA_BROKER_PORT=9092
      - KAFKA_BOOTSTRAP_SERVERS=http://localhost:9092
      - EXPOSED_ZOOKEEPER_PORT=2181
      - EXPOSED_KAFDROP_PORT=9999
    depends_on:
     - ims-db
    ports:
      - '8089:8089'

  ims-db:
    container_name: ims-db
    build: docker/db
    environment:
      - DB=ims
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${EXPOSED_DATABASE_PORT:-5432}:5432

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - ${EXPOSED_ZOOKEEPER_PORT:-2181}:2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - ${EXPOSED_KAFKA_BROKER_PORT:-9092}:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://:2${EXPOSED_KAFKA_BROKER_PORT:-9092},EXTERNAL://:${EXPOSED_KAFKA_BROKER_PORT:-9092}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:2${EXPOSED_KAFKA_BROKER_PORT:-9092},EXTERNAL://localhost:${EXPOSED_KAFKA_BROKER_PORT:-9092}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${EXPOSED_ZOOKEEPER_PORT:-2181}

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    links:
      - kafka
    ports:
      - ${EXPOSED_KAFDROP_PORT:-9999}:9000
    environment:
      - JVM_OPTS=-Xms32M -Xmx64M
      - KAFKA_BROKERCONNECT=kafka:2${EXPOSED_KAFKA_BROKER_PORT:-9092}
      - SERVER_SERVLET_CONTEXTPATH=/
