version: "3"

services:
  ims-db:
    build: db
    environment:
      - DB=ims
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${EXPOSED_DATABASE_PORT:-5432}:5432
