server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: ims

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost/ims?user=postgres&password=postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ims
  flyway:
    check-location: true
    locations: filesystem:/home/alex/project/AM-IMS/ims-backend/src/main/resources/

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
        javax:
          cache:
            missing_cache_strategy: create
        cache:
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false

flyway:
  migrations:
    enabled: true

ims:
  swagger:
    enabled: true

  system:
    id: ims
