DROP TABLE IF EXISTS "warehouses" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
DROP TABLE IF EXISTS "towns" CASCADE;
DROP TABLE IF EXISTS "counties" CASCADE;
DROP TABLE IF EXISTS "warehouse_town_coverages" CASCADE;

DROP SEQUENCE IF EXISTS "warehouse_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "towns_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "counties_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "warehouse_town_coverages_id_seq" CASCADE;