DROP SEQUENCE IF EXISTS "warehouse_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "address_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "towns_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "counties_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "warehouse_town_coverages_id_seq" CASCADE;

