CREATE SEQUENCE warehouse_id_seq START 1 INCREMENT 10;
CREATE SEQUENCE address_id_seq START 1 INCREMENT 10;
CREATE SEQUENCE towns_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE counties_id_seq START 1 INCREMENT 1;
CREATE SEQUENCE warehouse_town_coverages_id_seq START 1 INCREMENT 1;
